server.port=${PORT:3000}
app.country=${COUNTRY:Unknown}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:futurekawa}
spring.datasource.username=${DB_USER:futurekawa}
spring.datasource.password=${DB_PASSWORD:futurekawa_pwd}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=0
