server.port=${PORT:3000}
app.children-services=${CHILDREN_SERVICES:brazil=http://localhost:3101,ecuador=http://localhost:3102,colombia=http://localhost:3103}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=backend-mother
