apiVersion: 1

contactPoints:
  - orgId: 1
    name: FutureKawa Discord
    receivers:
      - uid: futurekawa-discord
        type: discord
        disableResolveMessage: false
        settings:
          url: ${DISCORD_WEBHOOK_URL}
          title: "[{{ .Status | toUpper }}] FutureKawa - {{ .CommonLabels.alertname }}"
          message: "{{ template \"default.message\" . }}"

policies:
  - orgId: 1
    receiver: FutureKawa Discord
    group_by:
      - grafana_folder
      - alertname
      - country
      - job
    group_wait: 30s
    group_interval: 2m
    repeat_interval: 15m
    routes:
      - receiver: FutureKawa Discord
        object_matchers:
          - [service, =, futurekawa]
