name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: futurekawa-deploy
  cancel-in-progress: false

jobs:
  deploy-local-infra:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: Show outputs
        run: terraform output
